[package]
name = "matrix-bot"
version = "2.0.0-beta.2"
authors = ["sparky8251 <sparky@possumlodge.me>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sparky8251/matrix-bot/"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
thiserror = "1.0"
ruma-client = "0.4"
log = "0.4"
pretty_env_logger = "0.4"
futures = "0.3"
regex = "1.3"
lazy_static = "1.4"
uom = "0.28"
graphql_client = "0.9"
ron = "0.6.0"

[dependencies.reqwest]
version = "0.10"
features = ["json"]

[dependencies.tokio]
version = "0.2"
features = ["signal", "macros"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.url]
version = "2.1"
features = ["serde"]
