[package]
name = "jellyfin-matrix-bot"
version = "0.1.0"
authors = ["sparky8251 <sparky@possumlodge.me>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sparky8251/jellyfin-matrix-bot/"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1

[dependencies]
toml = "0.5"
thiserror = "1.0"
ruma-client = "0.4"
directories = "2.0"
log = "0.4"
pretty_env_logger = "0.4"
futures = "0.3"
regex = "1.3"
lazy_static = "1.4"
anyhow = "1.0"
uom = "0.28"
rand = "0.7"
graphql_client = "0.9"

[dependencies.reqwest]
version = "0.10"
features = ["json"]

[dependencies.tokio]
version = "0.2"
features = ["signal", "macros"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.url]
version = "2.1"
features = ["serde"]
