[package]
name = "matrix-bot"
version = "2.0.0-beta.12"
authors = ["sparky8251 <sparky@possumlodge.me>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sparky8251/matrix-bot/"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
graphql_client = "0.9"
http = "0.2"
lazy_static = "1.4"
regex = "1.4"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "8da034ab835ef1d599cd146164dffda960275c06" }
ron = "0.6"
ruma = { git = "https://github.com/ruma/ruma", rev = "0f64a6e", features = ["client-api", "unstable-pre-spec"] }
ruma-client = { git = "https://github.com/ruma/ruma", rev = "0f64a6e" }
thiserror = "1.0"
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
uom = "0.31"
assign = "1.1"
serde_json = "1.0"
hmac = "0.10"
sha2 = "0.9"
hex-literal = "0.3"

[dependencies.reqwest]
version = "0.10"
features = ["json"]

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
rev = "8da034ab835ef1d599cd146164dffda960275c06"
default-features = false
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.0"
features = ["signal", "macros", "sync", "rt-multi-thread"]
