[general]
# These users are allowed to access admin features like
# Inviting the bot to rooms
# Requires at least 1
authorized_users = [
    '@demouser1:matrix.homeserver.com',
    '@demouser2:matrix.homeserver.com',
]

# Rooms in which help commands are authorized.
# If no rooms are specified, all rooms the bot is in are allowed.
# Optional
help_rooms = ['!randomalpha:homeserver.com']

# Enable bot feature to perform common imperial <--> metric conversions
# Only applies to commandless conversions
# Required
enable_unit_conversions = true

# Enable bot feature to correct users if they misspell project name
# Required
enable_corrections = false

# Used to exclude units from conversion if there is a space between
# the quanity and unit. Such as in the case of "Im getting a 404 in response"
# Chances are, you dont want to convert that 404 as if it were inches.
# DOES NOT disable unit conversion for 404in
# Optional
unit_conversion_exclusion = [
    'in',
]

# Only required if enable_corrections = true
insensitive_corrections = [
    'Jellyfish',
    'Jelly Fin',
]

# Only required if enable_corrections = true
sensitive_corrections = [
    'JellyFin',
    'jellyFin',
]

# Must have 2 replacements
# The first replacement is replaced with the user that triggered the correction
# The second replacement is replaced with the exact spelling of the configured
# correction that was triggered. This means that if "jellyfish" triggers,
# it will be replaced with "Jellyfish"
#
# NOTE: If your bot is in rooms with IRC, make sure the message below
# does not exceed 512 chars once replacements have taken place.
# If you do not do this, IRC users will be given a link to a long message upon triggering
# Only required if enable_corrections = true
correction_text = '''I'd just like to interject for a moment {}. What you're referring to as {}, is in fact, Jellyfin, or as I've recently taken to calling it, Emby plus Jellyfin. Jellyfin is not a media server unto itself, but a free component of a media server as defined by Luke Pulverenti. Through a peculiar turn of events, the version of Jellyfin which is widely used today is basically developed with slave labor. Please recognize the harm caused to the slaves by misnaming the project.'''

# List of rooms to exclude from correction feature.
# Must be internal room id and not an alias
# eg: "!randomalpha:homeserver.com" and NOT
# "#friendlyname:homeserver.com"
# Optional
correction_exclusion = ['!randomalpha:homeserver.com']

# The keys to match for linking urls
# If you define "docs" here "docs@link" will link "link"
# while "wiki@link" will fail
# Must be lowercase
# Only required if linkable urls are set below
link_matchers = [
    'docs',
]

#Required, do not set to empty either
webhook_token = "token"

# User url, account, and password bot will log in with
# Required
[matrix_authentication]
url = 'https://matrix.homeserver.com'
username = '@botuser:matrix.homeserver.com'
password = 'supersecretpassword'

# Access token used to perform graphql queries.
# Required if you have searchable repos
[github_authentication]
access_token = 'supersecretaccesstoken'

# Searchable github repos.
# Messages containing "jf#1234" or "jf #1234" will search
# repo "jellyfin/jellyfin" for issues and pulls, then link if found
# Optional
[searchable_repos]
jf = 'jellyfin/jellyfin'
jellyfin = 'jellyfin/jellyfin'
jf-web = 'jellyfin/jellyfin-web'
jellyfin-web = 'jellyfin/jellyfin-web'

# Linkable urls. Can link to anything with a url.
# messages containing "docs@hwa" or "docs @hwa" will link
# doc "https://jellyfin.org/docs/general/administration/hardware-acceleration.html"
# Optional
[linkable_urls]
hwa = 'https://jellyfin.org/docs/general/administration/hardware-acceleration.html'
network = 'https://jellyfin.org/docs/general/networking/index.html'

# Group pings. Can ping an arbitrary number of users in response to 
# messages containing "%backend" or "% frontend"
# Group alises can be made with '%group-name' in the config file. 
# Aliases will not expand aliases.
# Optional
[group_pings]
backend = ['@user1:matrix.homeserver.com', '@user2:matrix.homeserver.com']
frontend = ['%web', '%tui-client']
server = ['%backend']
web = ['@user3:matrix.homeserver.com']
tui-client = ['@user4:matrix.homeserver.com']
api = ['%backend', '%web', '@user5:matrix.homeserver.com'] # Will only be "@user5:matrix.homeserver.com"